AllCops:
  Excludes:
    - db/**
    - db/migrate/*
    - test/**

Rails:
  Enabled: true

Metrics/LineLength:
    Exclude:
      - config/**
      - config/deploy/**
      - config/environments/**
      - config/initializers/**

Metrics/MethodLength:
    Max: 15
