AllCops:
  Excludes:
    - db/**
    - db/migrate/*
    - test/**

Rails:
  Enabled: true

Rails/Output:
  Exclude:
    - config/deploy.rb

Rails/Exit:
  Exclude:
    - config/deploy.rb

Metrics/BlockLength:
  Exclude:
    - config/deploy.rb
    - config/routes.rb

Metrics/LineLength:
    Exclude:
      - config/**
      - config/deploy/**
      - config/environments/**
      - config/initializers/**

Metrics/MethodLength:
    Max: 15
